### ISSUE TITLE
installation issue glm

### ISSUE THREAD

**Issue by tapj** [RfastOfficial/Rfast#18]
Hi,

installation works well on windows 10 R 3.6 but failled on RedHat centOS with R 3.6.
It failled when compiling glm function. I tested old archive without success.

I also tried from github or CRAN. please find error output below:

thank you for any help

```
glm.cpp: In function ‘Rcpp::List glm_logistic(Rcpp::NumericMatrix, Rcpp::NumericVector, double, int)’:
glm.cpp:60:21: error: call of overloaded ‘isinf(double&)’ is ambiguous
     if ( isinf(negLL) || lambda[0]*ta/2 < tol || prevNegLL - negLL < lltol) {
                     ^
glm.cpp:60:21: note: candidates are:
In file included from /usr/include/features.h:375:0,
                 from /usr/include/c++/4.8.2/x86_64-redhat-linux/bits/os_defines.h:39,
                 from /usr/include/c++/4.8.2/x86_64-redhat-linux/bits/c++config.h:2097,
                 from /usr/include/c++/4.8.2/cmath:41,
                 from /home/tapju/R/x86_64-redhat-linux-gnu-library/3.6/Rcpp/include/Rcpp/platform/compiler.h:100,
                 from /home/tapju/R/x86_64-redhat-linux-gnu-library/3.6/Rcpp/include/Rcpp/r/headers.h:67,
                 from /home/tapju/R/x86_64-redhat-linux-gnu-library/3.6/Rcpp/include/RcppCommon.h:29,
                 from /home/tapju/R/x86_64-redhat-linux-gnu-library/3.6/RcppArmadillo/include/RcppArmadilloForward.h:26,
                 from /home/tapju/R/x86_64-redhat-linux-gnu-library/3.6/RcppArmadillo/include/RcppArmadillo.h:31,
                 from glm.cpp:3:
/usr/include/bits/mathcalls.h:202:1: note: int isinf(double)
 __MATHDECL_1 (int,isinf,, (_Mdouble_ __value)) __attribute__ ((__const__));
 ^
In file included from /home/tapju/R/x86_64-redhat-linux-gnu-library/3.6/Rcpp/include/Rcpp/platform/compiler.h:100:0,
                 from /home/tapju/R/x86_64-redhat-linux-gnu-library/3.6/Rcpp/include/Rcpp/r/headers.h:67,
                 from /home/tapju/R/x86_64-redhat-linux-gnu-library/3.6/Rcpp/include/RcppCommon.h:29,
                 from /home/tapju/R/x86_64-redhat-linux-gnu-library/3.6/RcppArmadillo/include/RcppArmadilloForward.h:26,
                 from /home/tapju/R/x86_64-redhat-linux-gnu-library/3.6/RcppArmadillo/include/RcppArmadillo.h:31,
                 from glm.cpp:3:
/usr/include/c++/4.8.2/cmath:608:3: note: constexpr bool std::isinf(long double)
   isinf(long double __x)
   ^
/usr/include/c++/4.8.2/cmath:604:3: note: constexpr bool std::isinf(double)
   isinf(double __x)
   ^
/usr/include/c++/4.8.2/cmath:600:3: note: constexpr bool std::isinf(float)
   isinf(float __x)
   ^
glm.cpp:69:17: error: call of overloaded ‘isinf(double&)’ is ambiguous
   if ( isinf(dev) )
                 ^
glm.cpp:69:17: note: candidates are:
In file included from /usr/include/features.h:375:0,
                 from /usr/include/c++/4.8.2/x86_64-redhat-linux/bits/os_defines.h:39,
                 from /usr/include/c++/4.8.2/x86_64-redhat-linux/bits/c++config.h:2097,
                 from /usr/include/c++/4.8.2/cmath:41,
                 from /home/tapju/R/x86_64-redhat-linux-gnu-library/3.6/Rcpp/include/Rcpp/platform/compiler.h:100,
                 from /home/tapju/R/x86_64-redhat-linux-gnu-library/3.6/Rcpp/include/Rcpp/r/headers.h:67,
                 from /home/tapju/R/x86_64-redhat-linux-gnu-library/3.6/Rcpp/include/RcppCommon.h:29,
                 from /home/tapju/R/x86_64-redhat-linux-gnu-library/3.6/RcppArmadillo/include/RcppArmadilloForward.h:26,
                 from /home/tapju/R/x86_64-redhat-linux-gnu-library/3.6/RcppArmadillo/include/RcppArmadillo.h:31,
                 from glm.cpp:3:
/usr/include/bits/mathcalls.h:202:1: note: int isinf(double)
 __MATHDECL_1 (int,isinf,, (_Mdouble_ __value)) __attribute__ ((__const__));
 ^
In file included from /home/tapju/R/x86_64-redhat-linux-gnu-library/3.6/Rcpp/include/Rcpp/platform/compiler.h:100:0,
                 from /home/tapju/R/x86_64-redhat-linux-gnu-library/3.6/Rcpp/include/Rcpp/r/headers.h:67,
                 from /home/tapju/R/x86_64-redhat-linux-gnu-library/3.6/Rcpp/include/RcppCommon.h:29,
                 from /home/tapju/R/x86_64-redhat-linux-gnu-library/3.6/RcppArmadillo/include/RcppArmadilloForward.h:26,
                 from /home/tapju/R/x86_64-redhat-linux-gnu-library/3.6/RcppArmadillo/include/RcppArmadillo.h:31,
                 from glm.cpp:3:
/usr/include/c++/4.8.2/cmath:608:3: note: constexpr bool std::isinf(long double)
   isinf(long double __x)
   ^
/usr/include/c++/4.8.2/cmath:604:3: note: constexpr bool std::isinf(double)
   isinf(double __x)
   ^
/usr/include/c++/4.8.2/cmath:600:3: note: constexpr bool std::isinf(float)
   isinf(float __x)
   ^
make: *** [glm.o] Error 1
ERROR: compilation failed for package ‘Rfast’
```
```
> sessionInfo()
R version 3.6.0 (2019-04-26)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS/LAPACK: /usr/lib64/R/lib/libRblas.so

```

**Comment by tapj** [comment]
ok this is related to https://github.com/RfastOfficial/Rfast/issues/8
