### ISSUE TITLE
Compilation error while updating to 2.1.2

### ISSUE THREAD

**Issue by leejm516** [RfastOfficial/Rfast#120]
**Describe the bug**
- I encountered a compilation error when updating Rfast to 2.1.2 on R 4.4.2. I updated it through BioConductor manager. A previous version had been compiled without any error.
```
clang++ -std=gnu++17 -I"/opt/R-4.4.2/lib64/R/include" -DNDEBUG -I../inst/include -I'/home/user1/R/x86_64-pc-linux-gnu-library/4.4/Rcpp/include' -I'/home/user1/R/x86_64-pc-linux-gnu-library/4.4/RcppArmadillo/include' -I'/home/user1/R/x86_64-pc-linux-gnu-library/4.4/RcppParallel/include' -I'/home/user1/R/x86_64-pc-linux-gnu-library/4.4/RcppZiggurat/include' -I/usr/local/include   -fopenmp -fpic  -march=x86-64-v2 -mtune=nehalem -O2 -pipe -flto=thin  -c rvmf.cpp -o rvmf.o
rvmf.cpp:71:27: error: variable '_beta' cannot be threadprivate because it is thread-local
   71 | #pragma omp threadprivate(_beta, _rng)
      |                           ^
rvmf.cpp:67:23: note: '_beta' defined here
   67 | thread_local BetaOne *_beta;
      |                       ^
rvmf.cpp:71:34: error: variable '_rng' cannot be threadprivate because it is thread-local
   71 | #pragma omp threadprivate(_beta, _rng)
      |                                  ^
rvmf.cpp:68:45: note: '_rng' defined here
   68 | thread_local Random::uniform<Random::real> *_rng;
      |                                             ^
2 errors generated.
```

**To Reproduce**
- I installed the Bioconductor package manager and ran the following commands.
```
> if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
> BiocManager::install()
```

**Expected behavior**
- Compiled as it should be expected.

**Desktop (please complete the following information):**
 - OS: Arch Linux on Kernel 6.6.67
 - R-Version: 4.4.2
 - Rfast-Version: 2.1.2
 - GCC-Version: Clang 18.1.8

**Additional context**
Some modified flags for building R: 
```
CFLAGS ='-march=x86-64-v2 -mtune=nehalem -O2 -pipe $(LTO)'
LDFLAGS='-fuse-ld=lld -Wl,-O2 -Wl,--sort-common -Wl,--as-needed'
LTO='-flto=thin'
```
